# Generated by Django 4.1.6 on 2023-02-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='bid',
        ),
        migrations.AddField(
            model_name='winner',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
